Add flush to the file write functions
adafruit/Adafruit_CircuitPython_Logging pull request #58
Opened 2024-06-03 03:58 UTC by ilikecake

Sorry for the churn. Further testing of the logging file handlers showed that they needed a `flush()` after the `write()` command in order for the contents of the log file to be updated in a reasonable time.

2024-06-03 12:24 UTC, dhalbert requested changes
In the CPython version of this library, `StreamHandler` provides a `flush()` operation, and so do its subclasses, such as `FileHandler`. 

I think the user should be able to use `flush()` as needed to guarantee that a log entry has been written to a file, but it should be optional. There are use cases where you don't want to always do a `flush()`. This change will cause more wear on the flash chips.

2024-06-04 00:46 UTC, ilikecake commented
Added a `flush()` function to the StreamHandler. It should be inherited by the file handler classes below it. There does not seem to be a good way to actually call this function, however. Do we also need to impelment the `shutdown()` function?

https://docs.python.org/3/library/logging.html#logging.shutdown

2024-06-04 01:24 UTC, ilikecake commented
How about this? I added a `flushHandlers()` function to the logger. This is not in the default python implementation of the logger, but I can't see any other way to force a flush of the handlers without accessing the semi-private `_handlers` list from user code.

2024-06-04 02:24 UTC, dhalbert commented
I am sorry! I have led you astray. It turns out the that in the CPython impl, `StreamHandler` flushes by default: https://github.com/python/cpython/blob/3bf7a5079c8d1845af98c145056e7ae1e102be43/Lib/logging/__init__.py#L1164.

If you didn't want this to happen, you can create your own handlers and have it implements a particular strategy. There is a superclass `BufferingHandler`, which has a `shouldFlush()` operation: https://github.com/python/cpython/blob/3bf7a5079c8d1845af98c145056e7ae1e102be43/Lib/logging/handlers.py#L1304

The CPython library has a `.handlers` public property which returns all the registered handlers. But apparently it's discouraged to use this to flush: https://stackoverflow.com/questions/13176173/python-how-to-flush-the-log-django.

We try not to add features to the CPython library API, so I'd be reluctant to add `flushHandlers()`. I'm thiking we should go back to your original auto-`flush()` in 337770e.

If desired, a  separate library could be added that would define a non-flushing file handler, not based on `StreamHandler`. I am not suggesting it is worth doing that now.

2024-06-05 02:13 UTC, ilikecake commented
Sounds good, I have reverted it back to calling `flush()` after `write()`.

2024-06-16 20:49 UTC, FoamyGuy approved these changes
This looks good to me. 

Thanks for working on this followup @ilikecake!

2024-06-16 20:49 UTC, merged